### PR TITLE
Revert the kevin command

### PR DESCRIPTION
**Pull request by KZiad**

### CODE REVIEW

**Comment by IrishTnT** [comment]
I advocate this.

**Comment by jasonli0616** [comment]
nooooo pls no 😢

**Comment by IrishTnT** [comment]
> 
> 
> nooooo pls no 😢

Ryan approved a denied suggestion.

**Comment by jasonli0616** [comment]
> > nooooo pls no 😢
> 
> Ryan approved a denied suggestion.

In his words,

"it's *my* bot" - ryan (in vc, after i showed him the denied suggestion)

**Comment by IrishTnT** [comment]
Then Ryan can approve or deny this pull request as Ryan sees fit.

**Comment by jasonli0616** [comment]
you know what, how about a compromise @IrishTnT 

you complained that the word "kevin" would create too many false positives
what if the command is "kevin," with a comma
such as `kevin, {command}` instead of `kevin command`

**Comment by IrishTnT** [comment]
That would then specify the false positives to just me, who adds a comma before or after a name.
We do not need the "kevin" command in my opinion at all.

**Comment by jasonli0616** [comment]
but its pretty funny

**Comment by IrishTnT** [comment]
I don't think it's funny, but in the end, Ryan chooses.

**Comment by KZiad** [comment]
I think it's funny, but it would get old real quick.

**Comment by jasonli0616** [comment]
Ouch.

**Pull request merged**
